
export interface Cities {
  name: string
  "topLevelDomain/0"?: string
  alpha2Code: string
  alpha3Code: string
  "callingCodes/0": string
  capital?: string
  "altSpellings/0"?: string
  "altSpellings/1"?: string
  subregion: string
  region: string
  population: number
  "latlng/0"?: number
  "latlng/1"?: number
  demonym: string
  area?: string
  "timezones/0": string
  "borders/0"?: string
  "borders/1"?: string
  "borders/2"?: string
  "borders/3"?: string
  "borders/4"?: string
  "borders/5"?: string
  nativeName: string
  numericCode: string
  "flags/svg": string
  "flags/png": string
  "currencies/0/code"?: string
  "currencies/0/name"?: string
  "currencies/0/symbol"?: string
  "languages/0/iso639_1": string
  "languages/0/iso639_2": string
  "languages/0/name": string
  "languages/0/nativeName": string
  "languages/1/iso639_1"?: string
  "languages/1/iso639_2"?: string
  "languages/1/name"?: string
  "languages/1/nativeName"?: string
  "languages/2/iso639_1"?: string
  "languages/2/iso639_2"?: string
  "languages/2/name"?: string
  "languages/2/nativeName"?: string
  "translations/br": string
  "translations/pt": string
  "translations/nl": string
  "translations/hr": string
  "translations/fa"?: string
  "translations/de": string
  "translations/es": string
  "translations/fr": string
  "translations/ja": string
  "translations/it": string
  "translations/hu": string
  flag: string
  "regionalBlocs/0/acronym"?: string
  "regionalBlocs/0/name"?: string
  cioc?: string
  independent: boolean
  "altSpellings/2"?: string
  "altSpellings/3"?: string
  gini?: string
  "borders/6"?: string
  "regionalBlocs/0/otherNames/0"?: string
  "regionalBlocs/0/otherNames/1"?: string
  "regionalBlocs/0/otherNames/2"?: string
  "regionalBlocs/0/otherNames/3"?: string
  "regionalBlocs/0/otherNames/4"?: string
  "regionalBlocs/1/acronym"?: string
  "regionalBlocs/1/name"?: string
  "regionalBlocs/1/otherNames/0"?: string
  "regionalBlocs/1/otherNames/1"?: string
  "regionalBlocs/1/otherNames/2"?: string
  "timezones/1"?: string
  "timezones/2"?: string
  "timezones/3"?: string
  "timezones/4"?: string
  "timezones/5"?: string
  "timezones/6"?: string
  "timezones/7"?: string
  "regionalBlocs/0/otherAcronyms/0"?: string
  "regionalBlocs/0/otherAcronyms/1"?: string
  "regionalBlocs/0/otherAcronyms/2"?: string
  "borders/7"?: string
  "altSpellings/4"?: string
  "altSpellings/5"?: string
  "altSpellings/6"?: string
  "currencies/1/code"?: string
  "currencies/1/name"?: string
  "currencies/1/symbol"?: string
  "altSpellings/7"?: string
  "altSpellings/8"?: string
  "regionalBlocs/1/otherAcronyms/0"?: string
  "topLevelDomain/1"?: string
  "borders/8"?: string
  "borders/9"?: string
  "borders/10"?: string
  "regionalBlocs/1/otherAcronyms/1"?: string
  "regionalBlocs/1/otherAcronyms/2"?: string
  "regionalBlocs/1/otherNames/3"?: string
  "borders/11"?: string
  "borders/12"?: string
  "borders/13"?: string
  "borders/14"?: string
  "borders/15"?: string
  "languages/3/iso639_1"?: string
  "languages/3/iso639_2"?: string
  "languages/3/name"?: string
  "languages/3/nativeName"?: string
  "languages/4/iso639_1"?: string
  "languages/4/iso639_2"?: string
  "languages/4/name"?: string
  "languages/4/nativeName"?: string
  "languages/5/iso639_2"?: string
  "languages/5/name"?: string
  "languages/5/nativeName"?: string
  "languages/6/iso639_2"?: string
  "languages/6/name"?: string
  "languages/6/nativeName"?: string
  "languages/7/iso639_2"?: string
  "languages/7/name"?: string
  "languages/7/nativeName"?: string
  "languages/8/iso639_1"?: string
  "languages/8/iso639_2"?: string
  "languages/8/name"?: string
  "languages/8/nativeName"?: string
  "timezones/8"?: string
  "timezones/9"?: string
  "timezones/10"?: string
  "timezones/11"?: string
  "timezones/12"?: string
  "timezones/13"?: string
  "callingCodes/1"?: string
  "currencies/2/code"?: string
  "currencies/2/name"?: string
  "currencies/2/symbol"?: string
  "topLevelDomain/2"?: string
  "languages/5/iso639_1"?: string
  "languages/6/iso639_1"?: string
  "languages/7/iso639_1"?: string
  "languages/9/iso639_1"?: string
  "languages/9/iso639_2"?: string
  "languages/9/name"?: string
  "languages/9/nativeName"?: string
}
